/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'EdwinBrown' at '3/21/17 4:19 PM' with Gradle 2.0
 *
 * @author EdwinBrown, @date 3/21/17 4:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
